# region project.properties
projectName=Advancements Fullscreen
projectDescription=A client-side mod that makes the advancements window bigger by expanding it to full screen. Continuation of the Advancements Enlarger mod.
projectVersion=1.4.0
# endregion

# region gradle.properties
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true
# endregion
