# region project.properties
projectName=Advancements Fullscreen
projectDescription=A client-side mod that makes the advancements window bigger by expanding it to full screen. Continuation of the Advancements Enlarger mod.
projectVersion=0.3.3
# endregion

# region gradle.properties
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
# endregion
